version: '3.8'

services:
  datadog-agent:
    image: datadog/agent:latest
    container_name: datadog-agent
    network_mode: bridge
    pid: host
    ports:
      - "127.0.0.1:8126:8126"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rwmake --version
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/datadog/:/var/run/datadog/
      - /etc/passwd:/etc/passwd:ro
    environment:
      - DD_API_KEY=9d6cbc2d18c52c6b3c8bc0f0bfe216ca
      - DD_SITE=datadoghq.com
      - DD_HOSTNAME=fcg-api
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS=name:datadog-agent
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_RECEIVER_SOCKET=/var/run/datadog/apm.socket
      - DD_PROCESS_CONFIG_PROCESS_COLLECTION_ENABLED=true

  fcg-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: fcg-api
    container_name: fcg-api
    depends_on:
      - datadog-agent
    network_mode: bridge
    ports:
      - "8080:80"
    volumes:
      - /var/run/datadog/:/var/run/datadog/
    environment:
      - DD_AGENT_HOST=host.docker.internal
      - DD_ENV=dev
      - DD_SERVICE=fcg-api
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_API_KEY=9d6cbc2d18c52c6b3c8bc0f0bfe216ca
    labels:
      com.datadoghq.tags.env: dev
      com.datadoghq.tags.service: fcg-api
      com.datadoghq.tags.version: 1.0.0
      com.datadoghq.ad.logs: '[{"source":"csharp","service":"fcg-api"}]'
