# .github/workflows/ci-docker.yml
name: CI – Build Image & Publish to Docker Hub

on:
  push:
    branches:
      - main           # ⚙️ só na main
  workflow_dispatch:

jobs:
  build-and-push:
    name: 📦 Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore & Build & Test
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release
          dotnet test 5.Tests/FCG.Tests/FCG.Tests.csproj --no-build --configuration Release --verbosity normal

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fcg-api:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/fcg-api:${{ github.sha }}
